### PR TITLE
Make badge

### PR DESCRIPTION
**Pull request by brettz9**
Builds on #6 (not familiar with codecov to know why failing, but it is passing under local code coverage).

- Docs: Mention `badge_output` is a path not a mere name
- Enhancement: Add binary for `makeBadgeFromJSONFile`
- Enhancement: Add `makeBadgeFromJSONFile` and `makeBadge`
- Refactoring: Use lower case for `badgeGenerator` since not a constructor

The `makeBadge` methods are useful in the likes of Cypress where one has to generate a badge after a JSON report has already been produced.

### CODE REVIEW

**Comment by brettz9** [comment]
I've rebuilt this as well, and it is now passing.

**Comment by brettz9** [comment]
Great, thanks! Would you mind preparing an npm release also? Thanks!

**Comment by brettz9** [comment]
Thanks for the release!

**Comment by ianpogi5** [comment]
@brettz9 no problem! Thanks for your hard work!

**Pull request merged**
