### PR TITLE
Badge v2, linting, reporter-options, npm updates

### PR DESCRIPTION
**Pull request by brettz9**
I have packed some different items in here, though I can easily make as separate PRs if you prefer, as they are in separate commits.

Let me know what you think.

`--reporter-options` are documented now at https://mochajs.org/#-reporter-option-option-o-option-reporter-options-option and `badge-up`'s v2 at https://github.com/yahoo/badge-up#v2-usage .

The switch to v2 API makes it a breaking change, as the color format has changed (though I could convert the old-style colors if you wanted).

### CODE REVIEW

**Comment by ianpogi5** [comment]
@brettz9 Thanks for your work. Since it has breaking change, can we put that in documentation?

**Comment by brettz9** [comment]
Sure, @ianpogi5 . I've added a commit. Let me know how that works for you.

**Comment by brettz9** [comment]
Do you think you can take a look to review this and the other PRs? I'd like to point to a stable version in my various repos if these can be merged... Thanks!

**Comment by ianpogi5** [comment]
Hi Brett,

Sorry I've been catching on my work backlog from the holidays. Will do my
best to merge them over the weekend.

Thanks for your contribution!

**Pull request merged**
