### PR TITLE
Ianpogi5/issue39

### PR DESCRIPTION
**Pull request by ianpogi5**

### CODE REVIEW

**Comment by ianpogi5** [comment]
@brettz9 I've fixed publish issue with npm. I removed GPR publish because it requires more steps. Let me know if you need it.

I've bumped the node version to 16.

**Review by brettz9 — APPROVED** [review]
I still haven't gotten much into GH Actions, but sounds good to me, thanks!

**Comment by brettz9** [comment]
If I can just let you handle this merge if it's ready...

**Comment by ianpogi5** [comment]
@brettz9 I've published v0.10.4. I just realized there's no image upload here. So I'll just put the steps here. 

1. Create a [release](https://github.com/ianpogi5/mocha-badge-generator/releases/new).
2. On the tags, create a new tag. example: v0.10.4 (make sure this is the same version in `package.json`).
3. Release title should also be the same as the tag.
4. Click `Generate release notes` button.
5. Click `Publish release`

**Comment by brettz9** [comment]
@ianpogi5 : I tried following the above steps (though step 2 before step 1 as a release needed a tag), but although I was able to follow the remaining steps, it doesn't seem to have triggered an npm release. Does it take a while?

**Comment by brettz9** [comment]
@ianpogi5 : Yeah, it didn't trigger a release for some reason.

**Comment by ianpogi5** [comment]
@brettz9 you need to look at the Actions log to find out what the error is.

**Comment by brettz9** [comment]
Great, thanks! Fixed the release, and I see it was possible to just update the tag and click "Update the release" on the release page to trigger the new attempt.

**Pull request merged**
