### PR TITLE
- npm: Add ignore file

### PR DESCRIPTION
**Pull request by brettz9**
No need for a new release for this, especially as excluding the tests and such doesn't change the size by more than half a KB, but figure it is just a good practice to keep things small.

### CODE REVIEW

**Comment by brettz9** [comment]
I've updated so this is now passing (was pointing to the SHA of a `badge-up` fork I had since amended).

I've also added the following:

- npm: Update `package-lock.json` and point to `badge-up` fork returning a Promise
- Testing: Allow text reporter on `npm test` script and ensure testing all files

**Comment by brettz9** [comment]
Hi @ianpogi5 : When do you think you might be able to take a look at this? It'd be great to point to a stable version for the cases where I've started using this. Thanks!

**Comment by ianpogi5** [comment]
Hi Bret, will check it out today.

**Comment by brettz9** [comment]
And just as a gentle reminder in case you might miss it due to my having commented on this PR, there is also #7 . Thanks!

**Pull request merged**
