### PR TITLE
Updated badge up

### PR DESCRIPTION
**Pull request by brettz9**
Builds on #2 and #4 to point to `badge-up` fork with known vulnerabilities removed by [updating devDeps](https://github.com/brettz9/badge-up/commit/326bbed67abe38bebbb35098cd38f0101f7eb80e).

### CODE REVIEW

**Comment by brettz9** [comment]
I don't think I noticed this had been failing, so I've updated this PR as well. The tests needed to be updated per changes from the updating of dependencies, though they look the same.

**Comment by brettz9** [comment]
Excellent, thanks for all the merges! Could I also trouble you for a new npm release?

**Comment by ianpogi5** [comment]
> Excellent, thanks for all the merges! Could I also trouble you for a new npm release?

Done! Thank you for your work!

**Comment by brettz9** [comment]
Wonderful, thank you!

**Pull request merged**
